const express=require("express");const db=require("../config/db");const authMiddleware=require("../middleware/authMiddleware");const router=express.Router();
let ready=false;
async function ensureColumns(){
  if(ready) return;
  const cols=[['business_name',"VARCHAR(255) NOT NULL DEFAULT 'DAS & CO'"],['email','VARCHAR(255) NULL'],['phone','VARCHAR(50) NULL'],['address','TEXT NULL'],['default_percentage','DECIMAL(6,3) NOT NULL DEFAULT 2'],['rate_24k','DECIMAL(12,2) NOT NULL DEFAULT 0'],['rate_22k','DECIMAL(12,2) NOT NULL DEFAULT 0'],['rate_18k','DECIMAL(12,2) NOT NULL DEFAULT 0']];
  for(const [name,def] of cols){const [rows]=await db.query('SHOW COLUMNS FROM business_settings LIKE ?',[name]);if(!rows.length) await db.query(`ALTER TABLE business_settings ADD COLUMN ${name} ${def}`);}
  ready=true;
}
router.get("/",authMiddleware,async(req,res)=>{try{await ensureColumns();const [rows]=await db.query("SELECT * FROM business_settings LIMIT 1");const r=rows[0]||{};res.json({success:true,settings:{business_name:r.business_name||"DAS & CO",email:r.email||"",phone:r.phone||"",address:r.address||"",opening_gold_balance:Number(r.opening_gold_balance||0),default_percentage:Number(r.default_percentage||2),rate_24k:Number(r.rate_24k||0),rate_22k:Number(r.rate_22k||0),rate_18k:Number(r.rate_18k||0)}});}catch(e){res.status(500).json({success:false,message:e.message});}});
router.put("/",authMiddleware,async(req,res)=>{try{await ensureColumns();const data={business_name:req.body.business_name||"DAS & CO",email:req.body.email||"",phone:req.body.phone||"",address:req.body.address||"",opening_gold_balance:Number(req.body.opening_gold_balance||0),default_percentage:Number(req.body.default_percentage||2),rate_24k:Number(req.body.rate_24k||0),rate_22k:Number(req.body.rate_22k||0),rate_18k:Number(req.body.rate_18k||0)};const [rows]=await db.query("SELECT id FROM business_settings LIMIT 1");if(rows.length){await db.query(`UPDATE business_settings SET business_name=?,email=?,phone=?,address=?,opening_gold_balance=?,default_percentage=?,rate_24k=?,rate_22k=?,rate_18k=? WHERE id=?`,[data.business_name,data.email,data.phone,data.address,data.opening_gold_balance,data.default_percentage,data.rate_24k,data.rate_22k,data.rate_18k,rows[0].id]);}else{await db.query(`INSERT INTO business_settings (business_name,email,phone,address,opening_gold_balance,default_percentage,rate_24k,rate_22k,rate_18k) VALUES(?,?,?,?,?,?,?,?,?)`,Object.values(data));}res.json({success:true,message:"Settings updated successfully",settings:data});}catch(e){res.status(500).json({success:false,message:e.message});}});module.exports=router;
